service:
  sentiment-analysis-url: https://019fc7b99f14.ngrok-free.app
server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/assessment-employee"
    username: "root"
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.validator: DEBUG

# JWT Configuration
jwt:
  secret: "mySecretKeyForAssessmentEmployeeSystemThatShouldBeLongEnoughForSecurity"
  expiration: 86400  # 24 hours in seconds

